# Generated by Django 4.2.1 on 2023-05-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.IntegerField()),
                ('cve', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('ip_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('alias', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port_id', models.IntegerField(primary_key=True, serialize=False)),
                ('port_number', models.IntegerField()),
                ('service', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scan_type', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('os', models.CharField(max_length=10)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scanner.ip')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_time', models.CharField(max_length=50)),
                ('scan_type', models.CharField(max_length=30)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scanner.ip')),
            ],
        ),
        migrations.CreateModel(
            name='IpPort',
            fields=[
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Scanner.scan')),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scanner.ip')),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scanner.port')),
            ],
        ),
        migrations.CreateModel(
            name='IpCve',
            fields=[
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Scanner.ip')),
                ('cve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Scanner.cve')),
            ],
        ),
    ]
