# Generated by Django 4.2.1 on 2023-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neterix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
